# Generated by Django 3.2 on 2021-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='live_url',
            field=models.URLField(blank=True),
        ),
    ]
