# Generated by Django 3.2 on 2021-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211006_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
