# Generated by Django 3.2 on 2021-10-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects_img/'),
        ),
    ]
